version: '3.9'

services:

  redis_storage:
    image: redis
    restart: always
    command: redis-server --save 5 1 --loglevel warning
    ports:
      - 6380:6379
    volumes:
      - $PWD/redis_storage:/data

  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - $PWD/mongo_datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: serhii
      MONGO_INITDB_ROOT_PASSWORD: serhii_pass
      MONGO_INITDB_DATABASE: assign-doctors-visit-db
